// Generated by https://quicktype.io

export interface Parametros {
    lat: number;
    lon: number;
}

export interface Ubicacion {
    departamento: Departamento;
    lat:          Parametros;
    lon:          Parametros;
    municipio:    Departamento;
    provincia:    Departamento;
}

export interface Departamento {
    id:     string;
    nombre: string;
}
